//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDangKyNgayLD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachDiemDanh
    {
        public int DanhSachDiemDanh_id { get; set; }
        public int MSSV { get; set; }
        public int Dot_id { get; set; }
        public string MaDiemDanh { get; set; }
        public System.DateTime ThoiGian { get; set; }
    
        public virtual TaoDotNgayLaoDong TaoDotNgayLaoDong { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
