//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDangKyNgayLD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuDangKy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuDangKy()
        {
            this.PhieuDuyets = new HashSet<PhieuDuyet>();
        }
    
        public int PhieuDangKy_id { get; set; }
        public long MSSV { get; set; }
        public Nullable<bool> LaoDongTheoLop { get; set; }
        public Nullable<bool> LaoDongCaNhan { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<int> TaoDotLaoDong_id { get; set; }
        public string TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuDuyet> PhieuDuyets { get; set; }
        public virtual TaoDotNgayLaoDong TaoDotNgayLaoDong { get; set; }
    }
}
