//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDangKyNgayLD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuXacNhanHoanThanh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuXacNhanHoanThanh()
        {
            this.SoNgayLaoDongs = new HashSet<SoNgayLaoDong>();
        }
    
        public int id { get; set; }
        public Nullable<int> MSSV { get; set; }
        public Nullable<int> phieuduyet { get; set; }
        public Nullable<int> NguoiXacNhan { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<System.DateTime> NgayXacNhan { get; set; }
        public string TrangThai { get; set; }
    
        public virtual PhieuDuyet PhieuDuyet1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoNgayLaoDong> SoNgayLaoDongs { get; set; }
        public virtual QuanLy QuanLy { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
