//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDangKyNgayLD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuDuyet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuDuyet()
        {
            this.PhieuXacNhanHoanThanhs = new HashSet<PhieuXacNhanHoanThanh>();
        }
    
        public int PhieuDuyet_id { get; set; }
        public Nullable<int> Nguoiduyet { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<int> PhieuDangKy { get; set; }
        public string TrangThai { get; set; }
    
        public virtual PhieuDangKy PhieuDangKy1 { get; set; }
        public virtual QuanLy QuanLy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuXacNhanHoanThanh> PhieuXacNhanHoanThanhs { get; set; }
    }
}
