//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDangKyNgayLD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanLy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuanLy()
        {
            this.PhieuDuyets = new HashSet<PhieuDuyet>();
            this.PhieuXacNhanHoanThanhs = new HashSet<PhieuXacNhanHoanThanh>();
        }
    
        public int Quanly_id { get; set; }
        public string Hoten { get; set; }
        public Nullable<bool> Gioitinh { get; set; }
        public string Diachi { get; set; }
        public string SoDienThoaiQuanLy { get; set; }
        public Nullable<int> TaiKhoan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuDuyet> PhieuDuyets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuXacNhanHoanThanh> PhieuXacNhanHoanThanhs { get; set; }
        public virtual TaiKhoan TaiKhoan1 { get; set; }
    }
}
