//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDangKyNgayLD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_QLNLD4ROLEEntities1 : DbContext
    {
        public DB_QLNLD4ROLEEntities1()
            : base("name=DB_QLNLD4ROLEEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Anh> Anhs { get; set; }
        public virtual DbSet<DanhSachDiemDanh> DanhSachDiemDanhs { get; set; }
        public virtual DbSet<Khoa> Khoas { get; set; }
        public virtual DbSet<Lop> Lops { get; set; }
        public virtual DbSet<PhieuDangKy> PhieuDangKies { get; set; }
        public virtual DbSet<PhieuDuyet> PhieuDuyets { get; set; }
        public virtual DbSet<PhieuXacNhanHoanThanh> PhieuXacNhanHoanThanhs { get; set; }
        public virtual DbSet<QuanLy> QuanLies { get; set; }
        public virtual DbSet<SinhVien> SinhViens { get; set; }
        public virtual DbSet<SoNgayLaoDong> SoNgayLaoDongs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<TaoDotNgayLaoDong> TaoDotNgayLaoDongs { get; set; }
        public virtual DbSet<VaiTro> VaiTroes { get; set; }
    }
}
