//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDangKyNgayLD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        public long MSSV { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string QueQuan { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<int> TaiKhoan { get; set; }
        public string SoDienThoaiSinhVien { get; set; }
        public Nullable<int> Lop_id { get; set; }
        public Nullable<int> Anh_id { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Deleted_at { get; set; }
    
        public virtual Anh Anh { get; set; }
        public virtual Lop Lop { get; set; }
        public virtual TaiKhoan TaiKhoan1 { get; set; }
    }
}
