//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDangKyNgayLD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SinhVien()
        {
            this.DanhSachDiemDanhs = new HashSet<DanhSachDiemDanh>();
            this.PhieuXacNhanHoanThanhs = new HashSet<PhieuXacNhanHoanThanh>();
            this.SoNgayLaoDongs = new HashSet<SoNgayLaoDong>();
        }
    
        public int MSSV { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string QueQuan { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<int> TaiKhoan { get; set; }
        public string SoDienThoaiSinhVien { get; set; }
        public Nullable<int> Lop_id { get; set; }
        public Nullable<int> Anh_id { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Deleted_at { get; set; }
    
        public virtual Anh Anh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhSachDiemDanh> DanhSachDiemDanhs { get; set; }
        public virtual Lop Lop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuXacNhanHoanThanh> PhieuXacNhanHoanThanhs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoNgayLaoDong> SoNgayLaoDongs { get; set; }
        public virtual TaiKhoan TaiKhoan1 { get; set; }
    }
}
