//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDangKyNgayLD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoNgayLaoDong
    {
        public int SoNgayLaoDong_id { get; set; }
        public long MSSV { get; set; }
        public Nullable<int> TongSoNgay { get; set; }
        public Nullable<int> Ma_phieu_xac_nhan { get; set; }
    
        public virtual PhieuXacNhanHoanThanh PhieuXacNhanHoanThanh { get; set; }
    }
}
