//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDangKyNgayLD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaoDotNgayLaoDong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaoDotNgayLaoDong()
        {
            this.DanhSachDiemDanhs = new HashSet<DanhSachDiemDanh>();
            this.PhieuDangKies = new HashSet<PhieuDangKy>();
        }
    
        public int TaoDotLaoDong_id { get; set; }
        public string DotLaoDong { get; set; }
        public string Buoi { get; set; }
        public string LoaiLaoDong { get; set; }
        public Nullable<int> GiaTri { get; set; }
        public string ThoiGian { get; set; }
        public Nullable<System.DateTime> NgayLaoDong { get; set; }
        public string KhuVuc { get; set; }
        public Nullable<System.DateTime> Ngayxoa { get; set; }
        public Nullable<int> SoLuongSinhVien { get; set; }
        public Nullable<bool> TrangThaiDuyet { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> NguoiTao { get; set; }
        public string MaDiemDanh { get; set; }
        public string TrangThaiDot { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhSachDiemDanh> DanhSachDiemDanhs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuDangKy> PhieuDangKies { get; set; }
    }
}
